# -*- coding: utf-8 -*-
"""escape character.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19unD1Wk8nu0HxhF4u6EQmaVgpRPl_GoP
"""

print ('Dia berkata : "Pergilah!"')

print ("Aku menimpali: \"Apakah kau ingin aku 'angkat kaki'?!\"")

print ("\\(^_^)/ (\\-_-/)")