# -*- coding: utf-8 -*-
"""manipulasi string 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wsBLcteBtuezp5J75BP0gxz0_TsT386w
"""

template = 'halo, saya %s dari %s'

print(template % ('lendis fabri', 'indonesia'))

template = 'halo, saya {nama} dari {asal}'
template_2 = 'saya suka makan {} dan minum {}'

print (template.format(nama = 'lendis fabri', asal = 'indonesia'))
print (template_2.format('nasi goreng', 'air putih'))

nama = 'lendis fabri'
asal = 'indonesia'

print(f'perkenalkan saya {nama} dari {asal}')

alamat = 'surabaya, jawa timur, indonesia'

print(alamat.split())

print(alamat.split(','))

print(alamat.split(', '))

print('🩷'.join(['aku', 'suka', 'phyton']))

print('❤'.join(alamat.split(', ')))

print('halo selamat pagi!'.upper())
print('halo selamat siang!'.upper())

print('APA KABAR?'.lower())

print('Lagi Dimana?'.lower())

print('daun tidak pernah membenci angin'.title())

print('Indonesia Adalah Negara Kepulauan'.swapcase())
print('aKu cInTa NeGeRiKu'.swapcase())

angka = '12345'
print('Index angka 3:', angka.find('3'))
print('Index angka 45:', angka.find('45'))
print('Index angka 35:', angka.find('35'))

asal = 'lampung'
print(asal.find('pung'))

ibu_kota = 'Jakarta'

print(ibu_kota.replace('a', 'i'))
print(ibu_kota.replace('kar', '❤'))
print(ibu_kota.replace('a', ''))

paragraf = 'Pada hari ini di temukan dua buah mangga di dalam keranjang'
x = paragraf.count('temu')

print(f'Kata "temu" muncul sebanyak {x} kali')