# -*- coding: utf-8 -*-
"""Manipulasi String.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ru4aaOUggj1BzXq8ifMErNPRFvYDfnh
"""

nama = 'Fara Kamila'
asal = "Indonesia"

print(nama)

print(asal)

print(nama + asal)

"""memanipulasi/menambahkan data bisa menggunakan [+ atau ,] contoh : print(nama + asal) atau print(nama, asal)"""

print("Halo, nama saya",nama)

"""kalau mau nambah variabel selalu tambahkan koma untuk memisah variabel. contoh : ("Halo, nama saya",nama)"""

print("Halo, nama saya ",nama, "asal saya dari ", asal)

data_lengkap = nama + asal

print (data_lengkap)

"""**string + non string**"""

asal_kota = "Bandar Lampung"
kode_pos = 35144

asal_kota_kode_pos = asal_kota + str(kode_pos)

print(asal_kota_kode_pos)

asal_kota_x3 = asal_kota * 3
print(asal_kota_x3)