# -*- coding: utf-8 -*-
"""operasi string fara kamila 2411012043

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FTi0GDigO1x4x1ecs2A13BWARp_EXNpE
"""

aberita = 'Ramai-ramai developer di seluruh dunia mulai menggunakan \
teks editor masa kini seperti Visual Studio Code, \
atom, sublime text, dan lain sebagainya.'

print('sublime text' in berita)  # output: True
print('notepad++' in berita)     # output: False

# Indexing String

nama = 'Lendis Fabri'

print(nama[4])   # output: i
print(nama[7])   # output: F
print(nama[-1])  # output: i
print(nama[-3])  # output: b

# Slicing String

judul = 'Pelajaran Matematika Untuk SD'

print(judul[0:5])   # output: Pelaj
print(judul[:10])   # output: Pelajaran
print(judul[10:15]) # output: Matem
print(judul[-1:-3]) # output:
print(judul[:-3])   # output: Pelajaran Matematika Untuk
print(judul[-5:])   # output: uk SD

# Menghitung panjang string

print(len('Indonesia'))  # output: 9
print(len('Malaysia'))   # output: 8