# -*- coding: utf-8 -*-
"""Tipe Data Casting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KEHJvgcZ4TISL4IsnVcgrb6PjAXPXmer
"""



"""Tipe data casting :

Memeriksa jenis tipe data
kita bisa memeriksa tipe data dasri suatu variabel dengan fungsi type() bawaan python.

example :
"""

nama = 'Budi'
usia = 20
lajang = True
print(type(nama))
print(type(usia))
print(type(lajang))

"""konversi tipe data adalah teknik yg mengubah nilai yg awalnya dari tipe data a menjadi tipe data b, kenapa dikonversi? karna tdk smua data itu valid"""

usia = input('masukan usia anda : ')
print(type(usia))

"""Konversi tipe data secara implisit

"""

a = 10/2
print(type(a))

b = 1/2
print(type(b))

"""konversi string ke numerik"""

panjang = int(input ('masukkan panjang :'))
lebar = float(input('masukkan lebar :'))

print('luas =', panjang * lebar)

"""Konversi numerik ke string"""

nama = 'Wudi'
tahun_lahir = 2000

print(nama + ' lahir di tahun ' + str(tahun_lahir))