# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hJI8KaT6d5tTMvLmz-4-A_63wzjbtXXq
"""

x = 50
y = 22
c = x + y

print(c)

print(20 + 12)

# Inisialisasi variabel x dengan nilai 50
x = 50
# Inisialisasi variabel y dengan nilai 22
y = 22
# Hitung penjumlahan x dan y, lalu simpan hasilnya di variabel c
c = x + y

# Cetak nilai dari c
print(c)