# -*- coding: utf-8 -*-
"""UTS COMPRO 2 FARA KAMILA 2411012043

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14oVvZC15jIboBlKHOH-LEcsSbqRB8kgQ
"""

# data dari soal uts
raw_log = "ID:001#NAMA:kopi susu gula aren#QTY:3#PRICE:18000;ID:002#NAMA:COFFEE LATTE#QTY:1#PRICE:25000"

# pecah transaksi berdasarkan tanda titik koma
# dapet dua bagian transaksi di sini
pecahan = raw_log.split(";")

# ambil data transaksi 1 dan 2 secara manual
t1 = pecahan[0]
t2 = pecahan[1]

# sekarang bongkar transaksi 1 pake tanda pagar
isi1 = t1.split("#")

# bersihin nama menu pesanan pertama, buat jadi Title Case
makan1 = isi1[1].replace("NAMA:", "")
makan1 = makan1.strip().title()

# ambil QTY dan harganya, terus ubah ke angka (integer)
q1 = isi1[2].replace("QTY:", "")
q1 = int(q1)
p1 = isi1[3].replace("PRICE:", "")
p1 = int(p1)

# lanjut bongkar transaksi 2
isi2 = t2.split("#")

# bersihin nama menu pesanan kedua
makan2 = isi2[1].replace("NAMA:", "")
makan2 = makan2.strip().title()

# ambil QTY dan harganya buat pesanan kedua
q2 = isi2[2].replace("QTY:", "")
q2 = int(q2)
p2 = isi2[3].replace("PRICE:", "")
p2 = int(p2)

# --- itung-itungan laporan ---
sub1 = q1 * p1
sub2 = q2 * p2
total_semua = sub1 + sub2

# --- cetak hasil akhirnya ---
# samain persis kayak gambar 1
print("======================================================")
print("            LAPORAN HARIAN KEDAI SOU SPACE            ")
print("======================================================")
print(f"{'MENU':<26} {'QTY':<5} {'HARGA':<10} {'SUBTOTAL'}")
print("------------------------------------------------------")

# tampilin baris datanya
print(f"{makan1:<26} {q1:<5} {p1:<10} {sub1}")
print(f"{makan2:<26} {q2:<5} {p2:<10} {sub2}")

print("------------------------------------------------------")
# total pendapatan hari ini
print(f"{'TOTAL PENDAPATAN HARI INI:':<32} Rp {total_semua}")
print("======================================================")